### ISSUE TITLE
Question on Decrypting with sodium

### ISSUE THREAD

**Issue by ocelhay** [r-lib/sodium#25]
To communicate securely some information, I have:

 1. generated a public and private keys with the following command:
```
openssl req -x509 -nodes -newkey rsa:2048 -keyout <institution-retained>-private-key.pem -out <institution-provided>-public-key.pem
```

 2. shared the `public-key.pem` to a colleague that has used it to encrypt a string.

 3. I am now provided with this encrypted string of the form:

```
"-----BEGIN PKCS7-----\nMIIB7...OuVDPw==\n-----END PKCS7-----"
```

**Using `sodium::simple_decrypt`, how could I use my private key (in a `.pem` file) to decrypt this string?**
I have seen that in sodium vignette but I am not sure how I can adapt it:
```
library(sodium)
key <- keygen()
pub <- pubkey(key)
# Encrypt message with pubkey
msg <- serialize(iris, NULL)
ciphertext <- simple_encrypt(msg, pub)

# Decrypt message with private key
out <- simple_decrypt(ciphertext, key)
stopifnot(identical(out, msg))
```

PS: I have not encrypted the string and therefore don't know how to provide a reproducible example.

**Comment by jeroen** [comment]
You need the openssl R package for this. Try the `openssl::read_p7b()` function.
