### ISSUE TITLE
Expose XChaCha20 cipher

### ISSUE THREAD

**Issue by coolbutuseless** [r-lib/sodium#27]
libsodium supports the XChaCha20 cipher which has a 24-byte nonce.  This extended nonce makes nonce re-use a non-issue (if crypgraphically secure random bytes are used). 

See: https://libsodium.gitbook.io/doc/advanced/stream_ciphers/xchacha20

I'm happy to attempt a PR if this is considered worthwhile.

**Comment by jeroen** [comment]
Sure go for it :)

Op do 9 mei 2024 13:42 schreef mikefc ***@***.***>:

**Comment by jeroen** [comment]
Fixed in https://github.com/r-lib/sodium/pull/28
